name: kyc_app_server
description: Starting point for a server.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  convert: ^3.1.1
  crypto: ^3.0.2
  dfunc: ^0.10.0
  dio: ^5.4.0
  drift: ^2.14.1
  drift_postgres: ^1.2.1
  postgres: ^3.2.0
  freezed_annotation: ^2.4.2
  get_it: ^7.7.0
  grpc: ^4.0.0
  image: ^4.2.0
  injectable: ^2.4.4
  intl: ^0.19.0
  mailer: ^6.1.2
  kyc_app_client:
    path: ../kyc_app_client
  kyc_client_dart:
    git:
      url: https://github.com/espresso-cash/kyc_client_dart.git
  protobuf: ^3.1.0
  retrofit: ^4.0.3
  solana: ^0.31.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  json_serializable: ^6.7.1
  lints: ">=3.0.0 <5.0.0"
  retrofit_generator: ^8.0.6
