name: kyc_partner_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  collection: ^1.18.0
  cryptography: ^2.7.0
  dfunc: ^0.10.0
  flutter:
    sdk: flutter
  flutter_json_view: ^1.1.4
  freezed_annotation: ^2.4.2
  grpc: ^4.0.0
  intl: ^0.19.0
  kyc_app_client:
    path: ../kyc_app_client
  kyc_client_dart:
    git:
      url: https://github.com/espresso-cash/kyc_client_dart.git
      ref: upd-api
  protobuf: ^3.1.0
  provider: ^6.1.2
  solana: ^0.31.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mews_pedantic: ^0.28.0

flutter:
  uses-material-design: true
