name: kyc_app_flutter
description: A new Flutter project

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  collection: ^1.18.0
  cryptography: ^2.7.0
  dfunc: ^0.10.0
  face_camera: ^0.1.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.2
  grpc: ^4.0.0
  intl: ^0.19.0
  kyc_app_client:
    path: ../kyc_app_client
  kyc_client_dart:
    git:
      url: https://github.com/espresso-cash/kyc_client_dart.git
      ref: upd-api
  path_provider: ^2.1.3
  protobuf: ^3.1.0
  provider: ^6.1.2
  solana: ^0.31.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mews_pedantic: ^0.28.0

flutter:
  uses-material-design: true
